namespace NovaLearn.Application.Common.Interfaces;

/// <summary>A file that has been written to storage.</summary>
/// <param name="Key">The opaque name it was stored under, generated by the store.</param>
/// <param name="SizeBytes">How much was actually written.</param>
public sealed record StoredFile(string Key, long SizeBytes);

/// <summary>
/// Somewhere to put uploaded bytes.
///
/// Deliberately small and free of any notion of a web request, so the local disk implementation
/// used in development can be swapped for object storage without the use cases noticing. The store
/// generates its own keys: callers never choose a path, which is what keeps a filename typed by a
/// user from ever reaching the filesystem.
/// </summary>
public interface IFileStorage
{
    /// <summary>
    /// Writes a stream and returns the key it was stored under.
    /// </summary>
    /// <param name="originalFileName">Used only to pick a safe extension for the generated key.</param>
    Task<StoredFile> SaveAsync(
        Stream content, string originalFileName, CancellationToken cancellationToken);

    /// <summary>Opens a stored file, or returns null when the key resolves to nothing.</summary>
    Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken);

    /// <summary>Removes a stored file. Succeeds quietly when it has already gone.</summary>
    Task DeleteAsync(string key, CancellationToken cancellationToken);
}
